services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  adapt:
    build: .
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - STATE=${STATE:-run}   # valeur par défaut = run
    volumes:
      - app-data:/data
    command: >
      sh -lc '
      case "$STATE" in
        install)
          rm -rf /data/app && npx adapt-security/at-utils install --prerelease /data/app
          ;;
        update)
          cd /data/app && npx adapt-security/at-utils update --prerelease .
          ;;
        run|*)
          cd /data/app && npm start
          ;;
      esac
      '
    restart: unless-stopped

volumes:
  mongo-data:
  app-data:
